# Generated by Django 2.2.1 on 2019-05-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='positions',
            field=models.ManyToManyField(to='adm.Position'),
        ),
    ]
