# Generated by Django 2.2.1 on 2019-05-28 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20190528_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='department',
            name='positions',
        ),
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adm.Department'),
            preserve_default=False,
        ),
    ]
