# Generated by Django 2.2.1 on 2019-05-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
