# Generated by Django 2.2.1 on 2019-05-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
